version: '3'
services:
   web:
     build: ./app/
     image: web
     ports: 
       - "5000:5000"
     depends_on:
      - redis
     environment:
      - FLASK_PORT=5000
     container_name: my-web-container
   
   redis:
    image: "redis:alpine"
    container_name: my-redis-container
 

